### PR TITLE
Fix wrong database configuration in symfony tutorial

### PR DESCRIPTION
**Pull request by gaelreyrol**
Database configuration instruction in Symfony tutorial does not work as variable injection only work with env file.

### CODE REVIEW

**Comment by KannarFr** [comment]
Does it only supports MySQL? :D

**Comment by gaelreyrol** [comment]
Meh :stuck_out_tongue:

**Comment by gaelreyrol** [comment]
Is it better ? @KannarFr

**Comment by KannarFr** [comment]
Yey!

**Pull request merged**
