### PR TITLE
Update clever tools cli docs

### PR DESCRIPTION
**Pull request by hsablonniere**

### CODE REVIEW

**Comment by divarvel** [comment]
Can you add a paragraph for AUR installations?

**Comment by urcadox** [comment]
With this change, the documentation does not link to the Git repository. I think it would be best to mention it and just say that installation from npm is not officially supported.

An alternative would be to have another page about contributing to clever-tools I guess.

Secondly, you can now remove the section about the libcurl version mismatch since nodegit is rebuilt from scratch and replace it with @divarvel's suggestion. :)

**Comment by hsablonniere** [comment]
@urcadox 

> With this change, the documentation does not link to the Git repository. I think it would be best to mention it and just say that installation from npm is not officially supported.

I changed the npm section to briefly advise to stop this method and use the other ones (as @cnivolle also proposed).

> An alternative would be to have another page about contributing to clever-tools I guess.

The readme should contain those docs, right? Do you want a contributing section just linking to the github repo?

**Comment by urcadox** [comment]
I think a very short contributing section with a link to the repo would be nice yes, people will think this is closed source otherwise (in my opinion).

**Pull request merged**
