### PR TITLE
Add image of github deployment branch select

### PR DESCRIPTION
**Pull request by gaelreyrol**
The area is not easy to find as it is between to bigger components, so I thought it might be useful to add a screenshot.

### CODE REVIEW

**Comment by BlackYoup** [comment]
Maybe a full screenshot would be better here, with a "selection" (like a red rectangle, idk) to point to the right part of the screenshot? I don't feel like it will be easier to find with such a small part of the information page. What do you think?

**Comment by gaelreyrol** [comment]
I agree but I can't provide a full screenshot with a clean "Clever Cloud" branding

**Comment by BlackYoup** [comment]
> I agree but I can't provide a full screenshot with a clean "Clever Cloud" branding

What do you mean by "a clean Clever Cloud branding"?

**Comment by gaelreyrol** [comment]
I mean a screenshot with Clever Cloud org for exemple not mine

**Comment by BlackYoup** [comment]
I don't think it matters much, I'm not sure we ever had a screenshot with the Clever Cloud organization displayed anyway. @ldoguin what's your thoughts on this?

**Comment by BlackYoup** [comment]
Thanks :)

**Pull request merged**
