### PR TITLE
Update pulsar.md

### PR DESCRIPTION
**Pull request by loicguillois**
replace ADDON_PULSAR_HTTP_URL with ADDON_PULSAR_WEB_URL

### CODE REVIEW

**Comment by KannarFr** [comment]
Hi @loicguillois,

Why this PR? The generated env var is `ADDON_PULSAR_HTTP_URL`. Do I miss something?

**Comment by loicguillois** [comment]
not for me 
image

**Comment by KannarFr** [comment]
Can you join us using support with the related addon_id and explain you want to talk to me. I'll fix this.

**Comment by KannarFr** [comment]
Can you reach us via support with the related addon_id and explain you want to talk to me. I'll fix this.

**Pull request closed without merging**
