### PR TITLE
Add Elastic Stack env variables

### PR DESCRIPTION
**Pull request by gaelreyrol**
The environment variables from the Elastic Stack addon were missing in the environment variables reference.

### CODE REVIEW

**Comment by BlackYoup** [comment]
I think it could be better to have a meaningful description of each environment variable, especially for Elasticsearch where some of them can be confusing depending on what you need to do.

**Comment by gaelreyrol** [comment]
It might be a bit repetitive, tell me what you think !

**Comment by gaelreyrol** [comment]
`ELASTIC_APM_SECRET_TOKEN` and `ELASTIC_APM_SERVER_URLS` are missing

**Comment by BlackYoup** [comment]
> It might be a bit repetitive, tell me what you think !

It might but it's better for users to explain what's the point of each variable, the name can be confusing for some :)

**Comment by BlackYoup** [comment]
Thanks :)

**Pull request merged**
