### PR TITLE
Add webpacker informations

### PR DESCRIPTION
**Pull request by vvenance**

### CODE REVIEW

**Comment by urcadox** [comment]
Isn't that necessary only during build? If so, we should advise users to use a dedicated build instance instead of changing scalability options.

**Comment by vvenance** [comment]
yes it is only during build

**Comment by urcadox** [comment]
"make sure to enable the dedicated build instance option in the information tab of your application"

**Comment by urcadox** [comment]
There's a double "make sure". Looks good otherwise.

**Pull request merged**
