### PR TITLE
matomo: add warning about plugins

### LINKED ISSUE #796: Matomo plugins: explain the current limitations
The documentation about [Customize your Matomo instance](https://www.clever-cloud.com/doc/deploy/addon/matomo/#customize-your-matomo-instance) explains how to add plugins but it does not mention the current limitations.

Plugins added through the Matomo UI need to be reinstalled everytime the instance reboots.

We should mention this in the documentation.

### PR DESCRIPTION
**Pull request by florian-sanders-cc**
Fixes #796 

Not quite sure about the syntax and how this "warning" will look. 
I took the example from the get started page.

Feel free to tell me what needs to be changed :+1:

### CODE REVIEW

**Comment by judu** [comment]
Is it still true?

**Comment by florian-sanders-cc** [comment]
I believe it is but let's ask @miton18 :eyes:

**Comment by florian-sanders-cc** [comment]
Alright @judu Miton confirmed that this is still true :+1: 

Shall we merge this?

**Review by RemiBardon — APPROVED** [review]
LGTM

**Pull request merged**
