### PR TITLE
Update default Postgres version number to 11.1

### PR DESCRIPTION
**Pull request by jvosloo**

### CODE REVIEW

**Comment by urcadox** [comment]
You can update the shared version to 11.1 as well! :D

**Comment by cnivolle** [comment]
Hi @jvosloo, 
Do you want to complete your PR with the edit proposed by @urcadox ? We can do it if you're okay with that.

**Comment by jvosloo** [comment]
@cnivolle I amended the change to 11.1 to the shared DBs as well.
Please check if you agree with the proposed update

**Comment by cnivolle** [comment]
All good! 👍

**Pull request merged**
